- id: '1739296703233'
  alias: Automatische verlichting badkamer
  description: Verlichting in de badkamer automatisch in- en uitschakelen op basis
    van de aanwezigheid van mensen
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.athom_presence_sensor_v3_ae0cb4_mmwave_sensor
      light_switch:
        entity_id: light.badkamer
- id: '1739297542705'
  alias: Wasmachine programma
  description: Monitoring van de wasmachine, informeren wanneer de wasmachine afgerond
    is.
  use_blueprint:
    path: Blackshome/appliance-notifications.yaml
    input:
      power_sensor: sensor.wasmachine_power
      start_appliance_power: 15
      end_time_delay: 5
      end_notify_device:
      - 91b326aa54d18ebc6b8e4a40d3c01a3b
      end_message_title: Wasmachine
      end_message: Programma afgerond
- id: '1739298215405'
  alias: Wasdroger programma
  description: Monitoring van de wasdroger, informeren wanneer de wasdroger is afgerond
  use_blueprint:
    path: Blackshome/appliance-notifications.yaml
    input:
      power_sensor: sensor.wasdroger_power
      include_end_notify: enable_end_notify_options
      end_notify_device:
      - 91b326aa54d18ebc6b8e4a40d3c01a3b
      end_message_title: Wasdroger
      end_message: Programma is afgerond
