- id: '1739296703233'
  alias: Automatische verlichting badkamer
  description: Verlichting in de badkamer automatisch in- en uitschakelen op basis
    van de aanwezigheid van mensen
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.athom_presence_sensor_v3_ae0cb4_mmwave_sensor
      light_switch:
        entity_id: light.badkamer
- id: '1739297542705'
  alias: Wasmachine programma
  description: Monitoring van de wasmachine, informeren wanneer de wasmachine afgerond
    is.
  use_blueprint:
    path: Blackshome/appliance-notifications.yaml
    input:
      power_sensor: sensor.wasmachine_power
      start_appliance_power: 15
      end_time_delay: 5
      end_notify_device:
      - 91b326aa54d18ebc6b8e4a40d3c01a3b
      end_message_title: Wasmachine
      end_message: Programma afgerond
- id: '1739298215405'
  alias: Wasdroger programma
  description: Monitoring van de wasdroger, informeren wanneer de wasdroger is afgerond
  use_blueprint:
    path: Blackshome/appliance-notifications.yaml
    input:
      power_sensor: sensor.wasdroger_power
      include_end_notify: enable_end_notify_options
      end_notify_device:
      - 91b326aa54d18ebc6b8e4a40d3c01a3b
      end_message_title: Wasdroger
      end_message: Programma is afgerond
- id: '1739385566617'
  alias: Automatische verlichting garage
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.aanwezigbeidsmelder_garage_presence
      light_switch:
        entity_id: light.garage
      time_delay: 1
- id: '1739394267767'
  alias: 'Spiegel uitzetten als lamp uitgaat '
  description: Schakel de spiegel uit als deze aanstaat en de lamp in de badkamer
    uit is
  triggers:
  - trigger: state
    entity_id:
    - light.badkamer
    to: 'off'
  conditions:
  - condition: state
    entity_id: switch.shelly1pmminig3_84fce639ee60_switch_0
    state: 'on'
  actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.shelly1pmminig3_84fce639ee60_switch_0
  mode: single
- id: '1739444034520'
  alias: Automatische verlichting op gang en overloop
  description: Verlichting op de gang en overloop inschakelen als deze op dit moment
    uit is tussen 06:00 en 08:00.
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.athom_presence_sensor_v3_ae0cb4_mmwave_sensor
    to: 'on'
  conditions:
  - condition: time
    after: 06:00:00
    before: 08:00:00
  - condition: and
    conditions:
    - condition: state
      entity_id: light.overloop
      state: 'off'
    - condition: state
      entity_id: light.gang
      state: 'off'
    enabled: false
  actions:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id:
      - light.overloop
      - light.gang
  mode: single
- id: '1739445875347'
  alias: Felijne wakker worden
  description: Schakel de lampen in zodra de tijd dit toestaat en wijzig de kleuren
    zodat bekend is of ze uit bed mag of niet.
  triggers:
  - trigger: time
    at: 06:00:00
    variables:
      color: orange
      brightness_pct: 2
      check: "{{\n  is_state('binary_sensor.werkdag', 'on') \n  and is_state('binary_sensor.schoolvakantie',
        'off')\n}}\n"
  - trigger: time
    at: 06:30:00
    variables:
      color: orange
      brightness_pct: 2
      check: "{{\n  is_state('binary_sensor.werkdag', 'off') \n  or is_state('binary_sensor.schoolvakantie',
        'on')\n}}\n"
  - trigger: time
    at: input_datetime.felijne_wakker_worden
    variables:
      color: green
      brightness_pct: 10
      check: "{{\n  is_state('binary_sensor.werkdag', 'on') \n  and is_state('binary_sensor.schoolvakantie',
        'off')\n}}\n"
  - trigger: time
    at:
      entity_id: input_datetime.felijne_wakker_worden
      offset: 00:15:00
    variables:
      color: green
      brightness_pct: 10
      check: "{{\n  is_state('binary_sensor.werkdag', 'off') \n  or is_state('binary_sensor.schoolvakantie',
        'on')\n}}\n"
  conditions:
  - condition: template
    value_template: '{{ check }}'
  - condition: state
    entity_id: input_boolean.vakantie_mode
    state: 'off'
  actions:
  - alias: Zet lamp aan op juiste instellingen
    action: light.turn_on
    data:
      brightness_pct: '{{ brightness_pct }}'
      color_name: '{{ color }}'
    target:
      entity_id: light.plafond_strip
  mode: single
- id: '1739448008868'
  alias: Container meldingen
  description: Verstuur notificatie zodra er morgen een container aan straat moet
  triggers:
  - trigger: time
    at: '19:30:00'
  conditions:
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.afvalinfo_home_trash_type_tomorrow
      state: geen
  actions:
  - action: notify.toppe
    data:
      title: Container
      message: Morgen moet {{ states('sensor.afvalinfo_home_trash_type_tomorrow')
        }} aan straat!
  mode: single
- id: '1739473380621'
  alias: 'Mechanische ventilatie '
  description: Sturing van mechanische ventilatie op basis van luchtvochtigheid in
    de badkamer
  use_blueprint:
    path: Blackshome/bathroom-humidity-exhaust-fan.yaml
    input:
      trigger: sensor.afgeleide_luchtvochtigheid_badkamer
      fan_switch:
        entity_id:
        - script.ventilatie_hoog
        - input_boolean.ventilatie_automatisch
      fan_speed_off:
      - script.ventilatie_automatisch
      - input_boolean.ventilatie_automatisch
      include_fan_speed: fan_speed_disabled
