- id: '1739296703233'
  alias: Automatische verlichting badkamer
  description: Verlichting in de badkamer automatisch in- en uitschakelen op basis
    van de aanwezigheid van mensen
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.athom_presence_sensor_v3_ae0cb4_mmwave_sensor
      light_switch:
        entity_id: light.badkamer
- id: '1739297542705'
  alias: Wasmachine programma
  description: Monitoring van de wasmachine, informeren wanneer de wasmachine afgerond
    is.
  use_blueprint:
    path: Blackshome/appliance-notifications.yaml
    input:
      power_sensor: sensor.wasmachine_power
      start_appliance_power: 15
      end_time_delay: 5
      end_notify_device:
      - 91b326aa54d18ebc6b8e4a40d3c01a3b
      end_message_title: Wasmachine
      end_message: Programma afgerond
- id: '1739298215405'
  alias: Wasdroger programma
  description: Monitoring van de wasdroger, informeren wanneer de wasdroger is afgerond
  use_blueprint:
    path: Blackshome/appliance-notifications.yaml
    input:
      power_sensor: sensor.wasdroger_power
      include_end_notify: enable_end_notify_options
      end_notify_device:
      - 91b326aa54d18ebc6b8e4a40d3c01a3b
      end_message_title: Wasdroger
      end_message: Programma is afgerond
- id: '1739385566617'
  alias: Automatische verlichting garage
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.aanwezigbeidsmelder_garage_presence
      light_switch:
        entity_id: light.garage
      time_delay: 0
- id: '1739394267767'
  alias: Spiegelverwarming
  description: Schakel de spiegel uit als deze aanstaat en de lamp in de badkamer
    uit is
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.athom_presence_sensor_v3_ae0cb4_mmwave_sensor
  conditions: []
  actions:
  - if:
    - condition: state
      entity_id: binary_sensor.athom_presence_sensor_v3_ae0cb4_mmwave_sensor
      state: 'off'
    then:
    - if:
      - condition: state
        entity_id: switch.shelly1pmminig3_84fce639ee60_switch_0
        state: 'on'
      then:
      - type: turn_off
        device_id: bbfeff9bfc729d71ae7fae6ace07b325
        entity_id: 39d7f3540fff16344e267ff1ef5d630c
        domain: switch
    else:
    - if:
      - condition: state
        entity_id: binary_sensor.shelly1pmminig3_84fce639ee60_input_0_input
        state: 'on'
      then:
      - type: turn_on
        device_id: bbfeff9bfc729d71ae7fae6ace07b325
        entity_id: 39d7f3540fff16344e267ff1ef5d630c
        domain: switch
  mode: single
- id: '1739444034520'
  alias: Automatische verlichting op gang en overloop
  description: Verlichting op de gang en overloop inschakelen als deze op dit moment
    uit is tussen 06:00 en 08:00.
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.athom_presence_sensor_v3_ae0cb4_mmwave_sensor
    to: 'on'
  conditions:
  - condition: time
    after: 06:00:00
    before: 07:00:00
  - type: is_on
    condition: device
    device_id: ef841681ef88a1cab8491afccc62ee88
    entity_id: 456c970f840276c8fcfb9e2e10cd0875
    domain: binary_sensor
  actions:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id:
      - light.overloop
      - light.gang
  mode: single
- id: '1739445875347'
  alias: Felijne wakker worden
  description: Schakel de lampen in zodra de tijd dit toestaat en wijzig de kleuren
    zodat bekend is of ze uit bed mag of niet.
  triggers:
  - trigger: time
    at: 06:00:00
    variables:
      color: orange
      brightness_pct: 2
      check: "{{\n  is_state('binary_sensor.werkdag', 'on') \n  and is_state('binary_sensor.schoolvakantie',
        'off')\n}}\n"
  - trigger: time
    at: 06:30:00
    variables:
      color: orange
      brightness_pct: 2
      check: "{{\n  is_state('binary_sensor.werkdag', 'off') \n  or is_state('binary_sensor.schoolvakantie',
        'on')\n}}\n"
  - trigger: time
    at: input_datetime.felijne_wakker_worden
    variables:
      color: green
      brightness_pct: 10
      check: "{{\n  is_state('binary_sensor.werkdag', 'on') \n  and is_state('binary_sensor.schoolvakantie',
        'off')\n}}\n"
  - trigger: time
    at:
      entity_id: input_datetime.felijne_wakker_worden
      offset: 00:15:00
    variables:
      color: green
      brightness_pct: 10
      check: "{{\n  is_state('binary_sensor.werkdag', 'off') \n  or is_state('binary_sensor.schoolvakantie',
        'on')\n}}\n"
  conditions:
  - condition: template
    value_template: '{{ check }}'
  - condition: state
    entity_id: input_boolean.vakantie_mode
    state: 'off'
  actions:
  - alias: Zet lamp aan op juiste instellingen
    action: light.turn_on
    data:
      brightness_pct: '{{ brightness_pct }}'
      color_name: '{{ color }}'
    target:
      entity_id: light.plafond_strip
  mode: single
- id: '1739448008868'
  alias: Container meldingen
  description: Verstuur notificatie zodra er morgen een container aan straat moet
  triggers:
  - trigger: time
    at: '19:30:00'
  conditions:
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.afvalinfo_home_trash_type_tomorrow
      state: geen
  actions:
  - action: notify.toppe
    data:
      title: Container
      message: Morgen moet {{ states('sensor.afvalinfo_home_trash_type_tomorrow')
        }} aan straat!
  mode: single
- id: '1739473380621'
  alias: Mechanische Ventilatie
  description: ''
  use_blueprint:
    path: Blackshome/bathroom-humidity-exhaust-fan.yaml
    input:
      trigger: sensor.afgeleide_luchtvochtigheid_badkamer
      fan_switch:
        entity_id:
        - script.ventilatie_hoog
        - input_boolean.ventilatie_hoog
      fan_speed_off:
      - input_boolean.ventilatie_automatisch
      - script.ventilatie_automatisch
      bathroom_humidity_sensor: sensor.klimaatsensor_badkamer_luchtvochtigheid
      manual_trigger: []
      include_manual_trigger: disable_manual_trigger
      manual_trigger_default_time_delay: 15
      include_fan_speed: fan_speed_off_enabled
      include_manual_fan_switch: disable_manual_fan_switch
      manual_fan_switch: []
      include_lights: lights_disabled
- id: '1739619783822'
  alias: Automatische verlichting binnen
  description: ''
  use_blueprint:
    path: Blackshome/smart-light.yaml
    input:
      include_ambient:
      - ambient_low
      - ambient_high
      ambient_light_sensor: sensor.lux_sensor
      light_switch:
        entity_id: scene.ik_ben_thuis
      end_scenes:
      - scene.alle_lampen_uit
      ambient_light_value: 199
      ambient_light_value_off: 200
- id: '1739621038843'
  alias: Automatische verlichting buiten
  description: ''
  use_blueprint:
    path: Blackshome/smart-light.yaml
    input:
      include_ambient:
      - ambient_low
      - ambient_high
      ambient_light_sensor: sensor.bh1750_illuminance
      light_switch:
        entity_id: scene.buiten_verlichting_inschakelen
      end_scenes:
      - scene.buiten_verlichting_uitschakelen
- id: '1739622361906'
  alias: Stofzuigen
  description: ''
  triggers:
  - trigger: time
    at: 00:02:00
  conditions:
  - condition: state
    entity_id: input_boolean.dagelijks_stofzuigen
    state: 'on'
  actions:
  - action: vacuum.start
    metadata: {}
    data: {}
    target:
      entity_id: vacuum.dreamebot_l10s_ultra
  mode: single
- id: '1739645487144'
  alias: Weltrusten
  description: Weltrusten!
  triggers:
  - trigger: state
    entity_id:
    - input_boolean.weltrusten
    to: 'on'
    id: weltrusten-schakelaar
  - trigger: time
    at: '23:00:00'
    id: weltrusten-tijd
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - weltrusten-schakelaar
      sequence:
      - action: script.weltrusten
        metadata: {}
        data: {}
    - conditions:
      - condition: trigger
        id:
        - weltrusten-tijd
      - condition: state
        entity_id: input_boolean.weltrusten
        state: 'off'
      sequence:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.alle_lampen_uit
  mode: single
- id: '1739645952309'
  alias: Schoonmaak deur/alarm
  description: Alarm in- of uitschakelen zodra de schoonmaak op donderdag tussen 08:00
    en 13:00 de deur ontgrendeld of vergrendeld
  triggers:
  - trigger: state
    entity_id:
    - lock.garage_deur
    to: unlocked
    id: ontgrendeld
  - trigger: state
    entity_id:
    - lock.garage_deur
    to: locked
    id: vergrendeld
  conditions:
  - condition: time
    weekday:
    - thu
    after: 08:00:00
    before: '13:00:00'
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - ontgrendeld
      sequence:
      - action: alarmo.disarm
        metadata: {}
        data:
          entity_id: alarm_control_panel.alarmo
    - conditions:
      - condition: trigger
        id:
        - vergrendeld
      sequence:
      - action: alarmo.arm
        metadata: {}
        data:
          mode: away
          skip_delay: false
          force: false
          entity_id: alarm_control_panel.alarmo
  mode: single
- id: '1739699667610'
  alias: Goedemorgen bij openen tussendeur
  description: ''
  triggers:
  - type: opened
    device_id: 4d661e7fad8f607da715791ab11d8dea
    entity_id: 99f3cadc232532705c904d9088d4bf0b
    domain: binary_sensor
    trigger: device
  conditions:
  - condition: state
    entity_id: input_boolean.goedemorgen
    state: 'off'
  actions:
  - if:
    - condition: numeric_state
      entity_id: sensor.lux_sensor
      below: 190
    then:
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: scene.ochtend_verlichting
    alias: Licht inschakelen bij minder dan 190 lux
  - action: alarmo.disarm
    metadata: {}
    data:
      entity_id: alarm_control_panel.alarmo
  - action: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.goedemorgen
  mode: single
- id: '1739699880879'
  alias: Schakelaars 's nachts uitzetten
  description: ''
  triggers:
  - trigger: time
    at: 02:00:00
  conditions: []
  actions:
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
      - input_boolean.goedemorgen
      - input_boolean.weltrusten
  mode: single
- id: '1739831435590'
  alias: Alarm vakantie
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - lock.garage_deur
    id: Ontgrendeld
    to: unlocked
  - trigger: state
    entity_id:
    - lock.garage_deur
    to: locked
    id: Vergrendeld
  conditions:
  - condition: state
    entity_id: input_boolean.vakantie_mode
    state: 'on'
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - Ontgrendeld
      sequence:
      - action: alarmo.disarm
        metadata: {}
        data:
          entity_id: alarm_control_panel.alarmo
    - conditions:
      - condition: trigger
        id:
        - Vergrendeld
      sequence:
      - action: alarmo.arm
        metadata: {}
        data:
          mode: away
          skip_delay: false
          force: false
          entity_id: alarm_control_panel.alarmo
  mode: single
- id: '1740342939410'
  alias: Nieuwe automatisering
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - climate.air_conditioner_493535_air_conditioner
    from: 'off'
  - type: opened
    device_id: 400ce30e8e123375c7faa01781658a45
    entity_id: a641c7f364e552b196a2ef272ff5d989
    domain: binary_sensor
    trigger: device
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: weather.forecast_home
        attribute: temperature
        below: 10
      sequence:
      - action: script.airco_notificatie_met_uitschakelen
        metadata: {}
        data:
          message: Het is {{ state_attr('weather.forecast_home', 'temperature') }}
            graden buiten en de airco staat aan.
      alias: Buiten onder de 10 graden
    - conditions:
      - condition: and
        conditions:
        - type: is_open
          condition: device
          device_id: 400ce30e8e123375c7faa01781658a45
          entity_id: a641c7f364e552b196a2ef272ff5d989
          domain: binary_sensor
        - condition: state
          entity_id: climate.air_conditioner_493535_air_conditioner
          state: cool
      sequence:
      - action: script.airco_notificatie_met_uitschakelen
        metadata: {}
        data:
          message: Raam is open...
  mode: single
- id: '1740418457430'
  alias: Airco knop
  description: ''
  triggers:
  - device_id: 6aa01485fc7997bc4cabe9501afe3401
    domain: zha
    type: remote_button_short_press
    subtype: remote_button_short_press
    trigger: device
    alias: Knop ingedrukt
  conditions:
  - condition: not
    conditions:
    - condition: time
      after: 08:00:00
      before: '17:00:00'
    alias: Het is niet tussen 08:00 en 17:00.
  actions:
  - if:
    - condition: device
      device_id: e347f109859b849973682a18eb9035b7
      domain: climate
      entity_id: fd3e977c81f83470d01430be45567c45
      type: is_hvac_mode
      hvac_mode: 'off'
    then:
    - device_id: e347f109859b849973682a18eb9035b7
      domain: climate
      entity_id: fd3e977c81f83470d01430be45567c45
      type: set_hvac_mode
      hvac_mode: cool
    else:
    - device_id: e347f109859b849973682a18eb9035b7
      domain: climate
      entity_id: fd3e977c81f83470d01430be45567c45
      type: set_hvac_mode
      hvac_mode: 'off'
    alias: Controleer airco
  mode: single
- id: '1740424187632'
  alias: Alarm aan/uit op personen in zone Home
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - zone.home
    to:
  conditions: []
  actions:
  - if:
    - condition: state
      entity_id: zone.home
      state: '0'
    - condition: state
      entity_id: input_boolean.gast_thuis
      state: 'off'
    then:
    - action: lock.lock
      metadata: {}
      data: {}
      target:
        entity_id: lock.garage_deur
    - action: alarmo.arm
      metadata: {}
      data:
        mode: away
        skip_delay: false
        force: false
        entity_id: alarm_control_panel.alarmo
    else:
    - action: lock.unlock
      metadata: {}
      data: {}
      target:
        entity_id: lock.garage_deur
    - action: alarmo.disarm
      metadata: {}
      data:
        entity_id: alarm_control_panel.alarmo
  mode: single
- id: '1740766262207'
  alias: Airco filter
  description: ''
  use_blueprint:
    path: tag-update-date.yaml
    input:
      scanned_tag: tag.actualiseer_airco_filter
      target_ent:
        entity_id: input_datetime.airco_filter_gereinigd
- id: '1740766447961'
  alias: Ventilatie filter
  description: ''
  use_blueprint:
    path: tag-update-date.yaml
    input:
      scanned_tag: tag.actualiseer_ventilatie_filter
      target_ent:
        entity_id: input_datetime.ventilatie_filter_vervangen
- id: '1740766672821'
  alias: Warmtepomp bijgevuld
  description: ''
  use_blueprint:
    path: tag-update-date.yaml
    input:
      scanned_tag: tag.warmtepomp_bijgevuld
      target_ent:
        entity_id: input_datetime.bijvullen_warmtepomp
- id: '1740766754216'
  alias: Zout bijgevuld
  description: ''
  use_blueprint:
    path: tag-update-date.yaml
    input:
      scanned_tag: tag.zout_bijgevuld
      target_ent:
        entity_id: input_datetime.zout_bijgevuld
