# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  name: !secret name
  temperature_unit: C
  time_zone: !secret timezone
  latitude: !secret latitude
  longitude: !secret longitude
  language: nl
  country: NL
  unit_system: metric
  elevation: -1
  customize:
    zone.home:
      radius: 30
  allowlist_external_dirs:
    - /config
  external_url: !secret external_url
  internal_url: "http://192.168.0.119:8123"
  packages: !include_dir_named include/integrations

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 192.168.0.0/24

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list include/sensors
fan: !include_dir_merge_list include/fan
binary_sensor: !include_dir_merge_list include/binary_sensor
template: !include_dir_merge_list include/template
