calculate_all_zones:
calculate_zone:
  target:
    entity:
      domain: sensor
update_all_zones:
update_zone:
  target:
    entity:
      domain: sensor
set_bucket:
  target:
    entity:
      domain: sensor
  fields:
    new_bucket_value:
      required: true
      example: -10
      default: 0
set_all_buckets:
  fields:
    new_bucket_value:
      required: true
      example: -10
      default: 0
reset_bucket:
  target:
    entity:
      domain: sensor
reset_all_buckets:
clear_all_weather_data:
set_all_multipliers:
  fields:
    new_multiplier_value:
      required: true
      example: 1.0
      default: 1.0
set_multiplier:
  target:
    entity:
      domain: sensor
  fields:
    new_multiplier_value:
      required: true
      example: 1.0
      default: 1.0