blueprint:
  name: Irrigation Unlimited adjust watering time for a single zone.
  description: Adjust watering times based on smart irrigation calculations.
  domain: automation
  input:
    irrigation_zone:
      name: Irrigation Zone
      description: Zone to irrigate
      selector:
        entity:
          filter:
          - device_class:
            - duration
          multiple: false
    unlimited_zone:
      name: Unlimited Zone
      description: Unlimited zone to irrigate
      selector:
        entity:
          filter:
          - domain:
            - binary_sensor
          multiple: false
    time_on:
      name: Time to turn on
      selector:
        time: {}
      default: '23:30:00'
  source_url: https://raw.githubusercontent.com/jeroenterheerdt/HAsmartirrigation/refs/heads/master/blueprints/automation/Irrigation%20Unlimited%20adjust%20time%20single%20zone.yaml
variables:
  duration: !input irrigation_zone
alias: Smart Irrigation adjustment
trigger:
  platform: time
  at: !input time_on
condition:
- condition: template
  value_template: '{{ (states(''duration'') | float(-1)) >= 0 }}'
action:
- service: irrigation_unlimited.adjust_time
  data:
    actual: '{{ timedelta(seconds=states(''duration'') | int(0)) }}'
    entity_id: !input unlimited_zone
mode: single
