substitutions:
  name: athom-smart-plug-v3-50e238
  friendly_name: Overkapping
  device_description: "Schakelaar voor LED onder de overkapping"
packages:
  Athom_Technology.Smart_Plug_V3: github://athom-tech/esp32-configs/athom-smart-plug.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: UvDYHELuNxOSCUxwFHA/BcB+3Hnnu2H50/k3Kg0Z0L8=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
